# Generated by Django 6.0.2 on 2026-02-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_message',
            field=models.CharField(blank=True, default='Open to suggestions', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
