# Generated by Django 6.0.2 on 2026-02-08 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-checked_in_at']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='eventinterest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('event', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='eventinterest',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_public',
        ),
        migrations.AddField(
            model_name='event',
            name='check_in_radius',
            field=models.IntegerField(default=100, help_text='Check-in radius in meters'),
        ),
        migrations.AddField(
            model_name='event',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('basketball', 'Basketball'), ('soccer', 'Soccer/Football'), ('golf', 'Golf'), ('tennis', 'Tennis/Racquet Sports'), ('running', 'Running/Jogging'), ('cycling', 'Cycling'), ('hiking', 'Hiking'), ('gym', 'Gym/Weightlifting'), ('yoga', 'Yoga/Pilates'), ('swimming', 'Swimming'), ('pickup_games', 'Pickup Games'), ('coffee', 'Coffee'), ('brunch', 'Brunch'), ('dinner', 'Dinner'), ('happy_hour', 'Happy Hour'), ('food_tour', 'Food Tour'), ('cooking', 'Cooking Together'), ('bar_hopping', 'Bar Hopping'), ('club', 'Club/Dancing'), ('live_music', 'Live Music Venue'), ('karaoke', 'Karaoke'), ('trivia', 'Trivia Night'), ('museums', 'Museums'), ('gallery', 'Gallery Opening'), ('theater', 'Theater/Performance'), ('art_class', 'Art Class/Workshop'), ('photo_walk', 'Photography Walk'), ('concert', 'Concert'), ('open_mic', 'Open Mic'), ('jam_session', 'Jam Session'), ('music_festival', 'Music Festival'), ('dj_night', 'DJ Night'), ('game_night', 'Game Night'), ('book_club', 'Book Club'), ('study', 'Study Session'), ('coworking', 'Coworking'), ('networking', 'Networking'), ('hangout', 'Just Hangout')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('food', 'Food & Drink'), ('sports', 'Sports & Fitness'), ('nightlife', 'Nightlife'), ('arts', 'Arts & Culture'), ('music', 'Music'), ('social', 'Social')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='eventchat',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventchat',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventchat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventinterest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='events.event'),
        ),
        migrations.AlterUniqueTogether(
            name='eventinterest',
            unique_together={('event', 'user')},
        ),
    ]
