# Generated by Django 6.0.2 on 2026-02-21 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_checkin_options_alter_event_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='min_attendees',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('ticketmaster', 'Ticketmaster'), ('eventbrite', 'Eventbrite')], max_length=20)),
                ('external_id', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=50)),
                ('venue_name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('external_url', models.URLField()),
                ('ticket_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('huddll_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['source', 'external_id'], name='events_exte_source_a7b6a8_idx'), models.Index(fields=['start_time', 'is_active'], name='events_exte_start_t_8468ed_idx'), models.Index(fields=['latitude', 'longitude'], name='events_exte_latitud_461f13_idx')],
            },
        ),
        migrations.CreateModel(
            name='HuddllForExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_private', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('external_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huddlls', to='events.externalevent')),
                ('huddll_event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'unique_together': {('external_event', 'huddll_event')},
            },
        ),
    ]
