# Generated by Django 6.0.2 on 2026-03-10 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_min_attendees_externalevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, help_text='The external/public event this Huddll is based on', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='huddlls', to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('user', 'User Created'), ('external', 'External/Ticketmaster'), ('huddll', 'Huddll (Private Group)')], default='user', max_length=20),
        ),
    ]
