# Generated by Django 6.0.3 on 2026-03-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_emoji_event_parent_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalevent',
            name='source',
            field=models.CharField(choices=[('ticketmaster', 'Ticketmaster'), ('eventbrite', 'Eventbrite'), ('walters', 'Walters Art Museum'), ('bma', 'Baltimore Museum of Art'), ('ottobar', 'Ottobar'), ('keystone', 'Keystone Korner'), ('andiemusik', 'An Die Musik'), ('metro', 'Metro Baltimore'), ('the8x10', 'The 8x10'), ('creativealliance', 'Creative Alliance'), ('mdhs', 'MD Center for History'), ('avm', 'American Visionary Art Museum')], max_length=20),
        ),
    ]
