# Generated by Django 6.0.3 on 2026-03-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_externalevent_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('place_type', models.CharField(choices=[('bar', 'Bar'), ('restaurant', 'Restaurant'), ('park', 'Park'), ('event_venue', 'Event Venue')], max_length=50)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(default='Baltimore', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('rating_count', models.IntegerField(blank=True, null=True)),
                ('price_level', models.IntegerField(blank=True, null=True)),
                ('is_open_now', models.BooleanField(blank=True, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('google_maps_url', models.URLField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-rating'],
                'indexes': [models.Index(fields=['place_type', 'is_active'], name='events_plac_place_t_f58381_idx'), models.Index(fields=['latitude', 'longitude'], name='events_plac_latitud_7c44eb_idx')],
            },
        ),
    ]
